# Site settings
title: "Lorena Carthy-Wimot"
description: "Digital Forensics and Cybersecurity"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lorena Carthy-Wilmot"
resume_title:                   "Digital Forensics & Cyber Security"

resume_contact_email:           "hei@lorenacw.com"

resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "addr • 00000 • hei@lorenacw.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Cybersecurity and digital forensics professional with experience across law enforcement, journalism, and consulting. Currently serving as a Journalistic Security Engineer at Schibsted, where I provide cybersecurity protection to uphold the integrity of journalists' work and secure their sensitive work in high-risk environments. Previously, I worked as a Special Investigator with the Norwegian Police, supporting complex criminal cases with advanced digital forensic expertise. At PwC Norway, I managed the Forensic Technology Services Lab, providing forensic capabilities to national teams and shaping investigative methodologies. </p>"

# yes, no leave blank
resume_looking_for_work:        ""

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_presentations:   true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

resume_social_links:
  resume_github_url:            "https://github.com/thisislola"
  resume_bluesky_url:           "https://bsky.app/profile/lorenacw.com"
  resume_linkedin_url:          "https://www.linkedin.com/in/LorenaCW"
  resume_medium_url:            "https://medium.com/@randomdent"
resume_print_social_links:      true

resume_theme:                   default

