# Site settings
title: "Lorena Carthy-Wimot"
description: "Digital Forensics and Cybersecurity"
url: "https://www.lorenacw.com"
baseurl: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Blog settings
permalink: /blog/:year/:month/:day/:title/

# Resume settings
resume_avatar:                  true
resume_name:                    "Lorena Carthy-Wilmot"
resume_title:                   "Digital Forensics & Cyber Security"

resume_contact_email:           "hei[at]lorenacw.com"

resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "Oslo, Norway â€¢ hei[at]lorenacw.com"
display_header_contact_info:    true

resume_header_intro: "<p>Cybersecurity and digital forensics professional with experience across law enforcement, journalism, and consulting. Currently serving as a Journalistic Security Engineer at Schibsted, where I provide cybersecurity protection to uphold the integrity of journalists' work and secure their sensitive work in high-risk environments. <br> Fluent in Spanish, English, Norwegian and Norwegian Sign Language.</p>"

# yes, no leave blank
resume_looking_for_work:        ""

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_presentations:   true
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       false

resume_social_links:
  resume_github_url:            "https://github.com/thisislola"
  resume_bluesky_url:           "https://bsky.app/profile/lorenacw.com"
  resume_linkedin_url:          "https://www.linkedin.com/in/LorenaCW"
  resume_medium_url:            "https://medium.com/@randomdent"
resume_print_social_links:      true

resume_theme:                   default

